// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Register.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ksn.leo.rpc.ice.register;

public interface RegisterWorker extends Ice.Object,
                                        _RegisterWorkerOperations, _RegisterWorkerOperationsNC
{
    public static final String ice_staticId = "::com::ksn::leo::rpc::ice::register::RegisterWorker";

    public static final long serialVersionUID = -3621290452262582732L;
}
