// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Register.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ksn.leo.rpc.ice.register;

public interface RegisterWorkerPrx extends Ice.ObjectPrx
{
    public RegisterResp register(RegisterReq req);

    public RegisterResp register(RegisterReq req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_register(RegisterReq req);

    public Ice.AsyncResult begin_register(RegisterReq req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_register(RegisterReq req, Ice.Callback __cb);

    public Ice.AsyncResult begin_register(RegisterReq req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_register(RegisterReq req, Callback_RegisterWorker_register __cb);

    public Ice.AsyncResult begin_register(RegisterReq req, java.util.Map<String, String> __ctx, Callback_RegisterWorker_register __cb);

    public Ice.AsyncResult begin_register(RegisterReq req, 
                                          IceInternal.Functional_GenericCallback1<RegisterResp> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_register(RegisterReq req, 
                                          IceInternal.Functional_GenericCallback1<RegisterResp> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_register(RegisterReq req, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<RegisterResp> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_register(RegisterReq req, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<RegisterResp> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public RegisterResp end_register(Ice.AsyncResult __result);
}
