// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Register.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ksn.leo.rpc.ice.register;

public final class RegisterWorkerHolder extends Ice.ObjectHolderBase<RegisterWorker>
{
    public
    RegisterWorkerHolder()
    {
    }

    public
    RegisterWorkerHolder(RegisterWorker value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof RegisterWorker)
        {
            value = (RegisterWorker)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _RegisterWorkerDisp.ice_staticId();
    }
}
