// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Login.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ksn.leo.rpc.ice.login;

public interface LoginWorkerPrx extends Ice.ObjectPrx
{
    public LoginResp login(LoginReq req);

    public LoginResp login(LoginReq req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_login(LoginReq req);

    public Ice.AsyncResult begin_login(LoginReq req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_login(LoginReq req, Ice.Callback __cb);

    public Ice.AsyncResult begin_login(LoginReq req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_login(LoginReq req, Callback_LoginWorker_login __cb);

    public Ice.AsyncResult begin_login(LoginReq req, java.util.Map<String, String> __ctx, Callback_LoginWorker_login __cb);

    public Ice.AsyncResult begin_login(LoginReq req, 
                                       IceInternal.Functional_GenericCallback1<LoginResp> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_login(LoginReq req, 
                                       IceInternal.Functional_GenericCallback1<LoginResp> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_login(LoginReq req, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_GenericCallback1<LoginResp> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_login(LoginReq req, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_GenericCallback1<LoginResp> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public LoginResp end_login(Ice.AsyncResult __result);
}
