// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Login.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ksn.leo.rpc.ice.login;

public class LoginResp implements java.lang.Cloneable, java.io.Serializable
{
    public String code;

    public String msg;

    public LoginResp()
    {
        code = "";
        msg = "";
    }

    public LoginResp(String code, String msg)
    {
        this.code = code;
        this.msg = msg;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        LoginResp _r = null;
        if(rhs instanceof LoginResp)
        {
            _r = (LoginResp)rhs;
        }

        if(_r != null)
        {
            if(code != _r.code)
            {
                if(code == null || _r.code == null || !code.equals(_r.code))
                {
                    return false;
                }
            }
            if(msg != _r.msg)
            {
                if(msg == null || _r.msg == null || !msg.equals(_r.msg))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::com::ksn::leo::rpc::ice::login::LoginResp");
        __h = IceInternal.HashUtil.hashAdd(__h, code);
        __h = IceInternal.HashUtil.hashAdd(__h, msg);
        return __h;
    }

    public LoginResp
    clone()
    {
        LoginResp c = null;
        try
        {
            c = (LoginResp)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(code);
        __os.writeString(msg);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        code = __is.readString();
        msg = __is.readString();
    }

    static public void
    __write(IceInternal.BasicStream __os, LoginResp __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public LoginResp
    __read(IceInternal.BasicStream __is, LoginResp __v)
    {
        if(__v == null)
        {
             __v = new LoginResp();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final LoginResp __nullMarshalValue = new LoginResp();

    public static final long serialVersionUID = 5216994809639732L;
}
