// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Login.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ksn.leo.rpc.ice.login;

public interface LoginWorker extends Ice.Object,
                                     _LoginWorkerOperations, _LoginWorkerOperationsNC
{
    public static final String ice_staticId = "::com::ksn::leo::rpc::ice::login::LoginWorker";

    public static final long serialVersionUID = -3838346832279456172L;
}
