// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Login.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ksn.leo.rpc.ice.login;

public final class LoginWorkerHolder extends Ice.ObjectHolderBase<LoginWorker>
{
    public
    LoginWorkerHolder()
    {
    }

    public
    LoginWorkerHolder(LoginWorker value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof LoginWorker)
        {
            value = (LoginWorker)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _LoginWorkerDisp.ice_staticId();
    }
}
